language: csharp
mono: none
dotnet: 2.1.4
dist: trusty
install:
  - dotnet restore
script:
  - dotnet build -c Release ./src/XWindowManager.sln
  - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./src/XWindowManager/bin/Release/XWindowManager*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    tags: true
    all_branches: true